color:
  brandColors:
    - '#FF6138'
    - '#FFFF9D'
    - '#BEEB9F'
    - '#79BD8F'
    - '#00A388'
  brandStrength: 0.6683430126868188
  lightness: 0.1698014645371586
  saturation: 0.6743588570971042
  rhythmicContrast: 0.521758880931884
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
name: Regen2energy
layout_spectrum: 0.7065111750271171
typography_spectrum: 0.32882050261832774
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: article
    html: >-
      <article><h1>Welcome to Solar Panels 4u</h1><p>Solar Panels 4u</p><img
      src="http://www.solarpanels4u.com/assets/images/solar-logo-1400x665.png"></article>
    src: 'http://www.solarpanels4u.com/assets/images/solar-logo-1400x665.png'
    metadata:
      author: []
      related: []
      publisher:
        url: 'http://www.solarpanels4u.com'
        name: Solarpanels4u
        favicon: >-
          http://www.solarpanels4u.com/assets/images/solar-logo-white-269x128.png
        domain: www.solarpanels4u.com
      keywords: []
      description: Solar Panels 4u
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      isBasedOnUrl: 'http://www.solarpanels4u.com/'
      title: Welcome to Solar Panels 4u
      datePublished: null
    title: Welcome to Solar Panels 4u
    caption: Solar Panels 4u
    text: !<tag:yaml.org,2002:js/undefined> ''
title: Regen2energy
description: Power When You Need It
purpose:
  - type: contact
    url: 'tel:017862306595'
    label: Call 017862306595
  - type: contact
    url: 'mailto:info@solarpanels4u.com'
    label: Contact me
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/63c5a5ce-21ab-41b7-b83a-172ca131fb3c.jpg
github: true
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/718ae849-7eb0-4a4d-82c8-c0ba61beb006.jpg
author:
  name: Ged Sloan
  email: info@solarpanels4u.com
  url: 'https://www.regen2energy.com'
opengraph:
  type: 'https://www.facebook.com/regen2energy/?fref=ts&ref=br_tf'
  appId: 'https://www.facebook.com/regen2energy/?fref=ts&ref=br_tf'
